Repository mia-ajuda/Backend, pull requests merged in 2023-04, with the labels that each got.

#148 222 - Eu, como usuário, desejo poder seguir outras pessoas no aplicativo, para que eu possa acessar seus perfis de maneira rápida
  src/controllers/SocialNetworkProfileController.js
  src/models/User.js
  src/repository/SocialNetworkRepository.js
  src/routes/SocialNetworkRoutes.js
Labels: enhancement, refactor

#149 Passa campos em comum para alguns modelos de dados envolvendo usuários
  src/repository/HelpOfferRepository.js
Labels: refactor

#150 US09 -Eu, como usuário, desejo poder visualizar perfis de outras pessoas no aplicativo Mia Ajuda para que possa compreender o que fizeram no aplicativo
  .eslintrc.json
  src/controllers/SocialNetworkProfileController.js
  src/repository/HelpOfferRepository.js
  src/repository/HelpRepository.js
  src/repository/SocialNetworkRepository.js
  src/services/SocialNetworkService.js
  src/utils/mapSocialNetworkUser.js
Labels: bug, refactor
